"""add revoked at to magic links

Revision ID: 0833031fd55d
Revises: d8e7be4cc277
Create Date: 2026-09-02 12:51:21.154415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0833031fd55d'
down_revision: Union[str, Sequence[str], None] = 'd8e7be4cc277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magic_links', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magic_links', 'revoked_at')
    # ### end Alembic commands ###
