"""add whatsapp users and update joins

Revision ID: 24d1320b4377
Revises: 516feecf6b11
Create Date: 2026-08-30 04:29:22.718832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d1320b4377'
down_revision: Union[str, Sequence[str], None] = '516feecf6b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_users',
    sa.Column('lid', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('lid')
    )
    op.add_column('whatsapp_joins', sa.Column('lid', sa.String(), nullable=False))
    op.create_foreign_key(None, 'whatsapp_joins', 'whatsapp_users', ['lid'], ['lid'])
    op.drop_column('whatsapp_joins', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_joins', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'whatsapp_joins', type_='foreignkey')
    op.drop_column('whatsapp_joins', 'lid')
    op.drop_table('whatsapp_users')
    # ### end Alembic commands ###
