"""add activity_recency_at to users

Revision ID: 397a28b2a3fd
Revises: 6f2c2cc5f243
Create Date: 2026-08-27 18:11:24.214172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397a28b2a3fd'
down_revision: Union[str, Sequence[str], None] = '6f2c2cc5f243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activity_recency_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activity_recency_at')
    # ### end Alembic commands ###
