"""add board membership status

Revision ID: 433daa3eee9e
Revises: dda8fafeeadd
Create Date: 2026-08-31 20:46:29.300534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433daa3eee9e'
down_revision: Union[str, Sequence[str], None] = 'dda8fafeeadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('board_membership_status', sa.String(), server_default='never', nullable=False))
    op.create_check_constraint('ck_student_profiles_board_membership_status', 'student_profiles', "board_membership_status IN ('current', 'former', 'never')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_student_profiles_board_membership_status', 'student_profiles', type_='check')
    op.drop_column('student_profiles', 'board_membership_status')
    # ### end Alembic commands ###
