"""add events and check ins

Revision ID: 4952712f5248
Revises: 433daa3eee9e
Create Date: 2026-09-01 01:53:09.352407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4952712f5248'
down_revision: Union[str, Sequence[str], None] = '433daa3eee9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rsvp_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rsvp_closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_check_in', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name='ck_events_ends_after_starts'),
    sa.CheckConstraint('rsvp_opens_at IS NULL OR rsvp_closes_at > rsvp_opens_at', name='ck_events_rsvp_closes_after_opens'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_users',
    sa.Column('workspace_user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('workspace_user_id')
    )
    op.create_table('event_rsvps',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(), nullable=False),
    sa.Column('has_paid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'user_id'),
    sa.UniqueConstraint('ticket_code')
    )
    op.create_table('event_check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(), nullable=False),
    sa.Column('workspace_user_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('qr', 'manual')", name='ck_event_check_ins_method'),
    sa.ForeignKeyConstraint(['ticket_code'], ['event_rsvps.ticket_code'], ),
    sa.ForeignKeyConstraint(['workspace_user_id'], ['workspace_users.workspace_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_check_ins')
    op.drop_table('event_rsvps')
    op.drop_table('workspace_users')
    op.drop_table('events')
    # ### end Alembic commands ###
