"""add whatsapp invite tables

Revision ID: 516feecf6b11
Revises: b900163aaa73
Create Date: 2026-08-29 21:08:06.983393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516feecf6b11'
down_revision: Union[str, Sequence[str], None] = 'b900163aaa73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_tickets',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('whatsapp_invites',
    sa.Column('wa_inv_link', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token'], ['whatsapp_tickets.token'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wa_inv_link')
    )
    op.create_table('whatsapp_joins',
    sa.Column('wa_inv_link', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wa_inv_link'], ['whatsapp_invites.wa_inv_link'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wa_inv_link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatsapp_joins')
    op.drop_table('whatsapp_invites')
    op.drop_table('whatsapp_tickets')
    # ### end Alembic commands ###
