"""remove whatsapp user names

Revision ID: 62705215844f
Revises: 24d1320b4377
Create Date: 2026-08-30 10:12:52.066197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62705215844f'
down_revision: Union[str, Sequence[str], None] = '24d1320b4377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_users', 'display_name')
    op.drop_column('whatsapp_users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('whatsapp_users', sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
