"""remove whatsapp join invite foreign key

Revision ID: 7086aac4351a
Revises: 62705215844f
Create Date: 2026-08-30 11:11:01.266633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7086aac4351a'
down_revision: Union[str, Sequence[str], None] = '62705215844f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('whatsapp_joins_wa_inv_link_fkey'), 'whatsapp_joins', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('whatsapp_joins_wa_inv_link_fkey'), 'whatsapp_joins', 'whatsapp_invites', ['wa_inv_link'], ['wa_inv_link'], ondelete='CASCADE')
    # ### end Alembic commands ###
