"""make ticket_code check-in pk

Revision ID: 949e02081805
Revises: 3bb91938f215
Create Date: 2026-09-06 18:05:06.584791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949e02081805'
down_revision: Union[str, Sequence[str], None] = '3bb91938f215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_check_ins_ticket_code_key'), 'event_check_ins', type_='unique')
    op.drop_column('event_check_ins', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_check_ins', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('event_check_ins_ticket_code_key'), 'event_check_ins', ['ticket_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
