"""add visibility and approval to student profiles

Revision ID: c57596d55eaa
Revises: d121b5708fa8
Create Date: 2026-08-27 22:52:07.601319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57596d55eaa'
down_revision: Union[str, Sequence[str], None] = 'd121b5708fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('is_visible', sa.Boolean(), nullable=False))
    op.add_column('student_profiles', sa.Column('is_approved', sa.Boolean(), nullable=False))
    op.add_column('student_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'created_at')
    op.drop_column('student_profiles', 'is_approved')
    op.drop_column('student_profiles', 'is_visible')
    # ### end Alembic commands ###
