"""create student profiles table

Revision ID: d121b5708fa8
Revises: 397a28b2a3fd
Create Date: 2026-08-27 22:19:13.490508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd121b5708fa8'
down_revision: Union[str, Sequence[str], None] = '397a28b2a3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(), nullable=False),
    sa.Column('second_major', sa.String(), nullable=True),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('minor', sa.String(), nullable=True),
    sa.Column('second_minor', sa.String(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.CheckConstraint("degree IN ('BS', 'BA', 'MS', 'MA', 'PhD')", name='ck_student_profiles_degree'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
