"""add whatsapp ticket user created index

Revision ID: dda8fafeeadd
Revises: 7086aac4351a
Create Date: 2026-08-31 03:18:44.544143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda8fafeeadd'
down_revision: Union[str, Sequence[str], None] = '7086aac4351a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_whatsapp_tickets_user_id_created_at', 'whatsapp_tickets', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_whatsapp_tickets_user_id_created_at', table_name='whatsapp_tickets')
    # ### end Alembic commands ###
